name: Build, Test and Deploy App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Test, Build And Deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.0
        with:
          node-version: 12.x
      - uses: bahmutov/npm-install@v1
      - name: Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - uses: codecov/codecov-action@v1

      - name: Build
        run: yarn build

      - name: Deploy to NPM
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
